# Generated by Django 2.1.2 on 2018-10-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('contact', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transaction_code', models.CharField(max_length=120)),
            ],
        ),
    ]
