# Generated by Django 2.1.2 on 2018-10-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20181025_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_price',
        ),
    ]
